apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{$npm_package_name}-deployment"
  labels:
    app: "{$npm_package_name}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{$npm_package_name}"
  template:
    metadata:
      labels:
        app: "{$npm_package_name}"
    spec:
      containers:
      - name: "{$npm_package_name}"
        image: "@{cells.cell89.registry}/{$npm_package_name}-{$npm_package_version}"
        ports:
        - containerPort: "@cells.cell89.port"
        resources:
          limits:
            cpu: "1"
            memory: 1024Mi
          requests:
            cpu: "50m"
            memory: 256Mi
        env:
        - name: CELL_MODE
          value: "_production+_secrets"
      imagePullSecrets:
      - name: gcr-json-key