apiVersion: v1
kind: Service
metadata:
  name: "{$npm_package_name}-service"
  labels:
    app: "{$npm_package_name}"
spec:
  ports:
  - name: http
    port: "@cells.cell89.port"
    protocol: TCP
    targetPort: "@cells.cell89.port"
  selector:
    app: "{$npm_package_name}"
  clusterIP: None